// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlY0ljw6fNhCWY4t6oczV--_tJgzDXwrc',
    appId: '1:27665052136:web:956e25568f9970fa23f45d',
    messagingSenderId: '27665052136',
    projectId: 'ecalibre-f2ea0',
    authDomain: 'ecalibre-f2ea0.firebaseapp.com',
    databaseURL: 'https://ecalibre-f2ea0-default-rtdb.firebaseio.com',
    storageBucket: 'ecalibre-f2ea0.firebasestorage.app',
    measurementId: 'G-L6WLZZ1VZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI3SKWVInIia6miu7PsX8y09SLWDtw2vU',
    appId: '1:27665052136:android:d8f8d136d00810c823f45d',
    messagingSenderId: '27665052136',
    projectId: 'ecalibre-f2ea0',
    databaseURL: 'https://ecalibre-f2ea0-default-rtdb.firebaseio.com',
    storageBucket: 'ecalibre-f2ea0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzBG6xmaJ7A2auuXT-WbMal_RIcVtuwfs',
    appId: '1:27665052136:ios:9fbb056dedf3f3e923f45d',
    messagingSenderId: '27665052136',
    projectId: 'ecalibre-f2ea0',
    databaseURL: 'https://ecalibre-f2ea0-default-rtdb.firebaseio.com',
    storageBucket: 'ecalibre-f2ea0.firebasestorage.app',
    iosBundleId: 'com.example.ecalibre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlY0ljw6fNhCWY4t6oczV--_tJgzDXwrc',
    appId: '1:27665052136:web:3f5966ef0d0aebb623f45d',
    messagingSenderId: '27665052136',
    projectId: 'ecalibre-f2ea0',
    authDomain: 'ecalibre-f2ea0.firebaseapp.com',
    databaseURL: 'https://ecalibre-f2ea0-default-rtdb.firebaseio.com',
    storageBucket: 'ecalibre-f2ea0.firebasestorage.app',
    measurementId: 'G-SBMFTQ2FTP',
  );

}